### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#10]
Look into various Continous Integrations options. If you upload code to MediaWiki directly they offer their own CI. There is also TravisCI.

the tricky part is will our tests be standalone or will we also have full integration tests w/ each MediaWiki version?

Needs #4 Tests completed or at least looked at to know.

**Comment by xSavitar** [comment]
Migrated to https://phabricator.wikimedia.org/T323434.
