### ISSUE TITLE
Realname links

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#11]
When you use a link style that only has the realname, it can become very difficult to link a user. The only way in that case to find a user's username is to look in the url.

* We could add it to the tooltip
* We could look at what MediaWiki hooks we have for processing links. Maybe we could add a `{#realnamelink:}` command, or even process `[[User:realname]]` links if they fail as usernames. The problem with this is that realnames are not unique, so we would have to deal with that somehow. Especially since when the link is made it may be unique, but down the line a new user could be made with the same realname.

**Comment by xSavitar** [comment]
Migrated to https://phabricator.wikimedia.org/T323433.
