### ISSUE TITLE
Error in mediawiki 1.36

### ISSUE THREAD

**Issue by ericrichtert** [ofbeaton/mediawiki-realnames#15]
In mediawiki 1.36, this extensions fails, because the $wgContLang is removed. 

See https://www.mediawiki.org/wiki/Manual:$wgContLang for the details.

This is used here:
https://github.com/ofbeaton/mediawiki-realnames/blob/3b1497b7f4ccb1b563e121ee16e5df0b02aaa4fd/src/Realnames.php#L258

**Comment by ofbeaton** [comment]
Thanks for the PR! merged.
