### ISSUE TITLE
Extension is marked as unmaintained on mediawiki.org

### ISSUE THREAD

**Issue by bertvandepoel** [ofbeaton/mediawiki-realnames#18]
We just learned about this extension and noticed that on https://www.mediawiki.org/wiki/Extension:Realnames there's a banner at the top claiming the extension is unmaintained, but then at the bottom it's clear that it is maintained to some degree (with the presumption being that when PRs arrive, new releases will be filed, and maintenance will sometimes be done if necessary).

Presumably one of these two parts is incorrect. Could this be looked into?

**Comment by ofbeaton** [comment]
I'm happy with it being marked as unmaintained, given I have no current way to test prs or releases, and have offered the extension to some people who have submitted high quality prs. I'm also not doing any code changes myself to keep it up to date. 

I've kept the extension online as it tends to be pretty robust and require little changes, and I know even if they have to manually patch it this functionality is very useful.

**Comment by bertvandepoel** [comment]
Oh I see, I was under the impression you were maintaining it for your employer. But that's no longer the case then?

**Comment by ofbeaton** [comment]
It is no longer the case, nor has it been for years I'm afraid.

**Comment by bertvandepoel** [comment]
I see, maybe the bottom section https://www.mediawiki.org/wiki/Extension:Realnames#Maintenance should then be updated? I'm not completely sure. It gave me that impression but technically it doesn't literally say so of course. Thanks for keeping the extension around though, that's very nice of you :)

**Comment by ofbeaton** [comment]
The top of the page and the sidebar mentions the whole page is unmaintained, so you can expect all the text to be out of date. But just in case it leads to further confusion, I've edited the section you mentioned. I'm glad you still find the extension useful!
