### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#3]
Before we can know how much optimisation we should do, it is important to get a repeatable benchmark to compare the current to any optimisation we test.

The biggest production load is likely Special:RecentChanges with 500 unique user page, made by 500 unique people. If you leave redirects, this results in 1500 usernames on screen, 1500 username -> realname replacements. Without redirects this is 1000 replacements and 500 misses (the old invalid names).

**Comment by ofbeaton** [comment]
I've done 500 changes on a wiki and displayed 500 replacements of only myself, and this was handled OK, but I don't have a benchmark tool for it.

**Comment by xSavitar** [comment]
Migrated to https://phabricator.wikimedia.org/T323438
