### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#4]
We need a test suite to be able to verify if the extension still works on a given MediaWiki version. It would be great if these tests could work on older versions of MediaWiki, but the PHPUnit files likely won't work, so once complete test coverage is achieved we will likely want to backport unit tests to hit older MediaWiki versions.

**Comment by xSavitar** [comment]
Migrated to https://phabricator.wikimedia.org/T323435
