### ISSUE TITLE
Batch DB calls

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#6]
Right now we locally cache within a single page load any db hits, but we do 1 db hit per name found. We could batch them up, dedup them, then do a single db hit. This would likely be a performance win. 

We would need #3 benchmarks before knowing if this is really a real concern however, and to know if this technique would help.

**Comment by xSavitar** [comment]
Migrated to https://phabricator.wikimedia.org/T323437
