### ISSUE TITLE
Timeless skin top right Username

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/mediawiki-realnames#7]
The Timeless skin added a new way to display the personal urls in the top right, and they are no longer replaced.

Look into how we can now do this replacement.

**Comment by ofbeaton** [comment]
I've filed an issue with upstream about this. https://phabricator.wikimedia.org/T215822

You can fix it by editing `skin/Timeless/TimelessTemplate.php` and make the changes I propose in the ticket above.

**Comment by samwilson** [comment]
Upstream bug has been fixed.

**Comment by ofbeaton** [comment]
Thank you for letting me know.
